language: node_js
sudo: required
dist: trusty

node_js:
  - "6"

addons:
  firefox: latest

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - npm run test:$TEST_MODE

env:
  - TEST_MODE=debug
  - TEST_MODE=prod
